# Generated by Django 3.0.8 on 2020-09-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rookie', '0004_auto_20200927_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='name',
            new_name='password',
        ),
    ]
